from setuptools import setup, find_packages

setup(
    name="college_feedback_system",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    description="A comprehensive feedback management system for educational institutions",
    author="College Feedback System Team",
    author_email="admin@example.com",
    url="https://github.com/yourusername/college-feedback-system",
    install_requires=[
        "Django>=4.2.7,<5.0.0",
        "djangorestframework>=3.14.0",
        "djangorestframework-simplejwt>=5.3.0",
        "django-cors-headers>=4.3.0",
        "Pillow>=10.1.0",
        "python-dotenv>=1.0.0",
        "python-decouple>=3.8",
        "django-filter>=23.3",
        "django-redis>=5.4.0",
        "drf-nested-routers>=0.94.1",
        "psutil>=5.9.8",
        "argon2-cffi>=23.1.0",
        "structlog>=25.2.0",
        "phonenumbers>=9.0.3",
    ],
    entry_points={
        "console_scripts": [
            "cfs-init-db=utils.db_scripts.initialize_db:initialize_database",
            "cfs-add-categories=utils.db_scripts.add_categories:add_categories",
            "cfs-create-test-users=utils.db_scripts.create_test_users:create_test_users",
            "cfs-fix-feedback=utils.db_scripts.fix_feedback_table:fix_feedback_table",
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 4.2",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    ],
    python_requires=">=3.8",
) 