# Generated by Django 5.2 on 2025-04-19 13:37

import django.core.validators
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/', validators=[feedback.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User satisfaction rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedbackcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['priority'], name='feedback_fe_priorit_fbe607_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category'], name='feedback_fe_categor_69b11d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['submitter'], name='feedback_fe_submitt_34dc49_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['assigned_to'], name='feedback_fe_assigne_0695b2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcategory',
            index=models.Index(fields=['name'], name='feedback_fe_name_dd45da_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackcategory',
            index=models.Index(fields=['active'], name='feedback_fe_active_4b5b91_idx'),
        ),
    ]
