# Generated by Django 4.2.7 on 2025-04-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedbacktag_notification_remove_feedbackcomment_user_and_more'),
    ]

    operations = [
    ] 