# Generated by Django 4.2.7 on 2025-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20250420_1556'),
        ('feedback', '0006_auto_20250420_1629'),
    ]

    operations = [
    ]
