# Generated by Django 4.2.7 on 2025-04-20 11:07

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_merge_0005_auto_20250420_1556_0006_auto_20250420_1629'),
    ]

    operations = [
        # Add content column if it doesn't exist
        migrations.RunSQL(
            """
            ALTER TABLE feedback_feedback ADD COLUMN content text DEFAULT 'No content provided';
            UPDATE feedback_feedback SET content = description;
            """,
            """
            ALTER TABLE feedback_feedback DROP COLUMN content;
            """
        ),
    ] 