# Generated by Django 4.2.7 on 2025-04-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20250420_1707'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS feedback_feedbackresponse (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content text NOT NULL,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                is_internal bool NOT NULL,
                attachment varchar(100) NULL,
                feedback_id bigint NOT NULL REFERENCES feedback_feedback (id),
                responder_id bigint NOT NULL REFERENCES accounts_user (id)
            );
            """,
            """
            DROP TABLE IF EXISTS feedback_feedbackresponse;
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE feedback_feedbacktag
            ADD COLUMN description text DEFAULT '';
            """,
            """
            ALTER TABLE feedback_feedbacktag
            DROP COLUMN description;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS feedback_feedbacktag_feedbacks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                feedbacktag_id bigint NOT NULL REFERENCES feedback_feedbacktag (id),
                feedback_id bigint NOT NULL REFERENCES feedback_feedback (id)
            );
            CREATE INDEX IF NOT EXISTS feedback_feedbacktag_feedbacks_tag_id_feedback_id_idx ON feedback_feedbacktag_feedbacks (feedbacktag_id, feedback_id);
            CREATE INDEX IF NOT EXISTS feedback_feedbacktag_feedbacks_feedback_id_idx ON feedback_feedbacktag_feedbacks (feedback_id);
            """,
            """
            DROP TABLE IF EXISTS feedback_feedbacktag_feedbacks;
            """
        ),
    ] 