# Generated by Django 4.2.7 on 2025-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_create_missing_tables'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Add user_id column if it doesn't exist
            ALTER TABLE feedback_feedback ADD COLUMN user_id bigint;

            -- Add user reference
            UPDATE feedback_feedback 
            SET user_id = COALESCE(submitter_id, 1)
            WHERE user_id IS NULL;
            
            -- Make sure we have the is_anonymous flag
            UPDATE feedback_feedback
            SET is_anonymous = 0
            WHERE is_anonymous IS NULL;
            """,
            """
            -- No rollback needed
            """
        ),
    ] 