# Generated by Django 4.2.7 on 2025-04-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_remove_is_anonymous'),
        ('feedback', 'migrate_user_to_submitter'),
    ]

    operations = [
    ]
