# Generated by Django 4.2.7 on 2025-04-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_populate_username_field'),
        ('accounts', '0005_add_username_field'),
    ]

    operations = [
    ]
